app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('dashboard/', include('admin_panel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('faq', views.FAQ, name='faq'),
    path('index', views.index, name='index'),
    path('car-list', views.car_list, name='car-list'),
    path('car_list/car_details/<int:car_id>', views.car_details, name='car_details'),
    path('partner-list', views.partner_list, name='partner-list'),
    path('add-opinion', views.add_opinion, name='add-opinion'),
    path('financing', views.financing, name='financing'),
    path('compare/', views.compare, name='compare'),
]

members/urls.py
from django.urls import path, include
from . import views

app_name = 'members'

urlpatterns = [
    path('login-user/', views.login_user, name='login-user'),
    path('dashboard/', include('admin_panel.urls', namespace='admin_panel')),
]

home/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save

class CarFuelType(models.Model):
    fuel_type = models.CharField('Rodzaj paliwa', max_length=50)

    def __str__(self):
        return self.fuel_type
    
class CarGear(models.Model):
    gear = models.CharField('Skrzynia biegów', max_length=50)

    def __str__(self):
        return self.gear
    
class vehicle_make(models.Model):
    make = models.CharField('Marka', max_length=50)

    def __str__(self):
        return self.make\
        
class yes_no(models.Model):
    yes_no = models.CharField('Wartość', max_length=3)

    def __str__(self):
        return self.yes_no



class Car(models.Model):
    car_make = [
        ('Audi', 'Audi'),
        ('BMW', 'BMW'),
        ('Ford', 'Ford'),
        ('Honda', 'Honda'),
        ('Hyundai', 'Hyundai'),
        ('Kia', 'Kia'),
        ('Mazda', 'Mazda'),
        ('Mercedes-Benz', 'Mercedes-Benz'),
        ('Nissan', 'Nissan'),
        ('Opel', 'Opel'),
        ('Renault', 'Renault'),
        ('Skoda', 'Skoda'),
        ('Toyota', 'Toyota'),
        ('Tesla', 'Tesla'),
        ('Volkswagen', 'Volkswagen'),
    ]

    fuel_type = [
        ('benzyna', 'Benzyna'),
        ('diesel', 'Diesel'),
        ('hybryda', 'Hybryda'),
        ('elektryczny', 'Elektryczny'),
        ('lpg', 'LPG'),
    ]

    gear_type = [
        ('Manualna', 'Manualna'),
        ('Automatyczna', 'Automatyczna'),
    ]

    type = [
        ('Używane', 'Używane'),
        ('Nowe', 'Nowe'),
    ]

    color = [
        ('Biały', 'Biały'),
        ('Szary', 'Szary'),
        ('Czarny', 'Czarny'),
        ('Srebrny', 'Srebrny'),
        ('Niebieski', 'Niebieski'),
        ('Czerwony', 'Czerwony'),
        ('Zielony', 'Zielony'),
        ('Żółty', 'Żółty'),
        ('Brązowy', 'Brązowy'),
        ('Inny', 'Inny')
    ]

    seats = [
        ('2', '2'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7 lub wiecej', '7 lub wiecej'),
    ]

    doors = [
        ('2/3', '2/3'),
        ('4/5', '4/5'),
    ]

    make = models.CharField('Marka', max_length=50, choices=car_make)
    model = models.CharField('Model', max_length=50)
    vin = models.CharField('VIN', max_length=17)
    year = models.IntegerField('Rok produkcji')
    price = models.IntegerField('Cena (PLN)')
    mileage = models.IntegerField('Przebieg (km)')
    description = models.TextField('Opis')
    engine_capacity = models.IntegerField('Pojemność silnika (cm3)')
    engine_power = models.IntegerField('Moc silnika (KM)')
    fuel_type = models.CharField('Rodzaj paliwa', max_length=50, choices=fuel_type)
    gear = models.CharField('Skrzynia biegów', max_length=50, choices=gear_type)
    type = models.CharField('Typ', max_length=50, choices=type)
    color = models.CharField('Kolor', max_length=50, choices=color)
    seats = models.CharField('Liczba miejsc', max_length=50, choices=seats)
    doors = models.CharField('Liczba drzwi', max_length=50, choices=doors)
    availability = models.BooleanField('Dostępność', default=False)
    image = models.ImageField('Zdjęcia', upload_to='images/',blank=True, null=True)

    def __str__(self):
        return str(self.make) + ' ' + self.model
    

class CarOnSale(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    special_offer = models.BooleanField('Promocja', default=False)
    new_price = models.IntegerField('Nowa cena (PLN)', blank=True, null=True)
    start_date = models.DateField('Data rozpoczęcia', blank=True, null=True)
    end_date = models.DateField('Data zakończenia', blank=True, null=True)
    
    def __str__(self):
        return str(self.car)
    
class Clients(models.Model):
    name = models.CharField('Imię i nazwisko / Nazwa firmy', max_length=50)
    pesel = models.IntegerField('PESEL', blank=True, null=True)
    nip = models.IntegerField('NIP', blank=True, null=True)
    adress = models.CharField('Adres', max_length=100)
    city = models.CharField('Miasto', max_length=50)
    zip = models.IntegerField('Kod pocztowy')
    phone = models.IntegerField('Telefon')
    email = models.EmailField('Email')
    

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    name = models.CharField('Imię i nazwisko', max_length=50)
    adress = models.CharField('Adres', max_length=100)
    city = models.CharField('Miasto', max_length=50)
    zip = models.IntegerField('Kod pocztowy')
    phone = models.IntegerField('Telefon')
    email = models.EmailField('Email')
    position = models.CharField('Stanowisko', max_length=50)
    hire_date = models.DateField('Data zatrudnienia')
    fire_date = models.DateField('Data zwolnienia', blank=True, null=True)
    
    def __str__(self):
        return self.name
    
class Order_status(models.Model):
    status = models.CharField('Status', max_length=50)
    
    def __str__(self):
        return self.status

class Orders(models.Model):
    order_number = models.BigAutoField(primary_key=True)
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    order_date = models.DateField('Data transakcji')
    order_price = models.IntegerField('Kwota transakcji')
    order_status = models.ForeignKey(Order_status, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.client.name + ' | ' + self.car.make + ' ' + self.car.model
 
class Contact(models.Model):
    name = models.CharField('Imię i nazwisko', max_length=50)
    email = models.EmailField('Email')
    message = models.TextField('Wiadomość')
    answer = models.ForeignKey(yes_no, on_delete=models.CASCADE, default=1)
    
    def __str__(self):
        return self.name

class client_opinion(models.Model):
    SCORE_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]

    client_name = models.CharField(max_length=100)
    client_mail = models.EmailField(max_length=100)
    client_score = models.CharField(choices=SCORE_CHOICES, max_length=1)
    client_opinion = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    rodo = models.BooleanField()
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.client_name

home/forms.py
from django import forms
from django.forms import ModelForm
from .models import Clients, Orders, Contact, Car
from admin_panel.models import *
from django.forms.widgets import NumberInput
from django.contrib.admin.widgets import AdminDateWidget

class DateInput(forms.DateInput):
    input_type = 'date'

class ClientsForm(ModelForm):
    class Meta:
        model = Clients
        fields = ('name', 'pesel', 'nip', 'adress', 'city', 'zip', 'phone', 'email')

        labels = {
            'name': '',
            'pesel': '',
            'nip': '',
            'adress': '',
            'city': '',
            'zip': '',
            'phone': '',
            'email': '',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Imię i nazwisko / Nazwa firmy'}),
            'pesel': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'PESEL'}),
            'nip': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'NIP'}),
            'adress': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Adres'}),
            'city': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Miasto'}),
            'zip': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Kod pocztowy'}),
            'phone': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Numer telefonu'}),
            'email': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Adres email'}),
        }

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message')

        labels = {
            'name': '',
            'email': '',
            'message': '',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Imię i nazwisko'}),
            'email': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Adres email'}),
            'message': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Wiadomość'}),
        }

class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = ('make', 'model', 'vin', 'year', 'price', 'mileage', 'description', 'engine_capacity', 'engine_power', 'fuel_type', 'gear', 'image')

        labels = {
            'make': '',
            'model': '',
            'year': '',
            'mileage': '',
            'engine_capacity': '',
            'engine_power': '',
            'fuel_type': '',
            'gear': '',
            'vin': '',
            'price': '',
            'description': '',
            'image': '',
        }

        widgets = {
            'make': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Marka'}),
            'model': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Model'}),
            'year': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Rok produkcji'}),
            'mileage': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Przebieg'}),
            'engine_capacity': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Pojemność silnika'}),
            'engine_power': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Moc silnika'}),
            'fuel_type': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Rodzaj paliwa'}),
            'gear': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Skrzynia biegów'}),
            'vin': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Numer VIN'}),
            'price': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Cena'}),
            'description': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Opis'}),
            'image': forms.FileInput(attrs={'class':'form-control', 'placeholder':'Zdjęcie'}),
        }

class ClientOpinionForm(ModelForm):
    class Meta:
        model = client_opinion
        fields = ('client_name', 'client_mail', 'client_score', 'client_opinion', 'rodo')

        labels = {
            'client_name' : '', 
            'client_mail' : '', 
            'client_score' : '', 
            'client_opinion' : '', 
            'rodo' : 'Zgoda RODO',
        }

        widgets = {
            'client_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Imię i nazwisko'}),
            'client_mail': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Adres email'}),
            'client_score': forms.Select(attrs={'class':'form-control', 'placeholder':'Ocena'}),
            'client_opinion': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Opinia'}),
            'rodo': forms.CheckboxInput(attrs={'class':'form-check-input', 'label':'Akceptuję warunki RODO'}),
        }

class CarFilterForm(forms.Form):
    class Meta:
        model = Car
        fields = ('make', 'model', 'year', 'mileage', 'engine_capacity', 'engine_power', 'fuel_type', 'gear')

        labels = {
            'make': '',
            'model': '',
            'year': '',
            'mileage': '',
            'engine_capacity': '',
            'engine_power': '',
            'fuel_type': '',
            'gear': '',
        }

        widgets = {
            'make': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Marka'}),
            'year': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Rok produkcji'}),
            'mileage': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Przebieg'}),
            'engine_capacity': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Pojemność silnika'}),
            'engine_power': forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Moc silnika'}),
            'fuel_type': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Rodzaj paliwa'}),
            'gear': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Skrzynia biegów'}),
        }

home/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from .filters import CarFilter
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages


def home(request):
    submitted = False
    opinion = client_opinion.objects.all()
    caronsale = CarOnSale.objects.all()
    car = Car.objects.all()
    today = timezone.now().date()

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return HttpResponseRedirect('/index?submitted=True')
    else:
        contact_form = ContactForm
        if "submitted" in request.GET:
            submitted = True

    return render(request, 'index.html',
                  {'contact_form': contact_form, 'submitted': submitted, 'opinion': opinion, 'caronsale': caronsale, 'car': car, 'today': today})



def FAQ(request):
    return render(request, 'FAQ.html', {})

def index(request):
    submitted = False
    opinion = client_opinion.objects.all()
    caronsale = CarOnSale.objects.all()
    car = Car.objects.all()
    today = timezone.now().date()

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return HttpResponseRedirect('/index?submitted=True')
    else:
        contact_form = ContactForm
        if "submitted" in request.GET:
            submitted = True

    return render(request, 'index.html',
                  {'contact_form': contact_form, 'submitted': submitted, 'opinion': opinion, 'caronsale': caronsale, 'car': car, 'today': today})

def car_list(request):
    car_list = Car.objects.all()

    # Filtering
    car_filter = CarFilter(request.GET, queryset=car_list)
    car_list = car_filter.qs

    # Sorting
    sort_by = request.GET.get('sort_by')

    if sort_by in ['make', 'model', 'price', 'year']:
        car_list = car_list.order_by(sort_by)
    
    return render(request, 'Car_List.html', 
                  {'car_list': car_list, 'filter': car_filter})



def car_details(request, car_id):
    car = Car.objects.get(pk=car_id)
    return render(request, 'Car_Details.html', 
                  {'car': car})

def partner_list(request):
    return render(request, 'partner_list.html', {})

def add_opinion(request):
    submitted = False
    
    if request.method == 'POST':
        form = ClientOpinionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Pojawiła się nowa opinia')
            return HttpResponseRedirect(reverse('home:home') + '?submitted=True')
    else:
        form = ClientOpinionForm
        if "submitted" in request.GET:
            submitted = True

    return render(request, 'add_opinion.html',
                  {'form': form, 'submitted': submitted})

def financing(request):
    return render(request, 'financing.html', {})

def compare(request):
    compare_list = request.GET.getlist('compare')
    car_list = Car.objects.filter(id__in=compare_list)
    return render(request, 'compare.html', {'car_list': car_list})

home/templates/Car_List.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<section class="section-background">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-xs-12">
                <div class="form-group">
                    <select class="form-control" id="sort-select" onchange="location = this.value;">
                        <option value="?">Domyślne sortowanie</option>
                        <option value="?sort_by=make">Sortowanie wg: marki</option>
                        <option value="?sort_by=model">Sortowanie wg: modelu</option>
                        <option value="?sort_by=price">Sortowanie wg: ceny</option>
                        <option value="?sort_by=year">Sortowanie wg: roku</option>
                    </select>
                </div>

                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading p-3 mb-3" role="tab" id="heading0">
                            <h3 class="panel-title">
                                <a class="collapsed" role="button" title="" data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0">
                                    FILTRY
                                </a>
                            </h3>
                        </div>
                        <div id="collapse0" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading0">
                            <div class="panel-body px-3 mb-4">
                                <form method="get">
                                    <div class="form-group">
                                        {{ filter.form.as_p }}
                                    </div>                                    
                                    <button type="submit" class="section-btn btn btn-primary btn-block">Filtruj</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <a id="compare-button" class="btn btn-primary" href="#" disabled>Porównaj samochody</a>

            </div>

            <div class="col-lg-9 col-xs-12">
                <div class="row">
                    {% for car in car_list %}
                        {% if car.availability == True %}
                        <div class="col-lg-6 col-md-4 col-sm-6">
                            <div class="courses-thumb courses-thumb-secondary">
                                <div class="courses-top">

                                    <div class="courses-image">
                                        {% if car.image %}
                                            <img src="{{car.image.url}}" class="img-responsive" alt="" style="max-width: 100%; object-fit: cover;">
                                        {% else %}
                                            <div class="no-image-icon">
                                                <i class="fa fa-car"></i>
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="courses-date">
                                        <span title="Przebieg"><i class="fa fa-dashboard"></i>
                                            {{car.mileage}} km
                                        </span>
                                        <span title="Pojemność silnika"><i class="fa fa-cube"></i>
                                            {{ car.engine_capacity }} cm<sup>3</sup>
                                        </span>
                                        <span title="Rodzaj skrzyni biegów"><i class="fa fa-cog"></i>
                                            {{ car.gear }}
                                        </span>
                                    </div>            
                                </div>
                
                                <div class="courses-detail">
                                    <h3><a href="car-details.html">
                                        {{car.make}} {{car.model}}
                                    </a></h3>
                
                                    <p class="lead"><strong>
                                        {{car.price}} PLN
                                    </strong></p>
                
                                    <p>
                                        {{car.engine_power}} KM&nbsp;&nbsp;/&nbsp;&nbsp;
                                        {{car.fuel_type}}&nbsp;&nbsp;/&nbsp;&nbsp;
                                        {{car.year}}
                                        
                                    </p>
                                </div>
                                
                                <div class="courses-info">
                                    <a href="{% url 'home:car_details' car.id %}" class="section-btn btn btn-primary btn-block">Więcej informacji</a>
                                    <input type="checkbox" class="compare-checkbox" value="{{ car.id }}"> Porównaj
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

<style>
    .courses-image {
        height: 200px; /* lub inną stałą wysokość */
        overflow: hidden; /* ukrywa nadmiarowe piksele obrazu */
        position: relative; /* ustawia pozycję względem rodzica */
    }
    .no-image-icon {
        position: absolute; /* ustawia pozycję względem rodzica */
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: #f5f5f5; /* lub inny kolor tła */
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 50px;
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        let compareList = [];
        const compareCheckboxes = document.querySelectorAll('.compare-checkbox');
    
        compareCheckboxes.forEach(checkbox => {
            checkbox.addEventListener('change', (e) => {
                const carId = e.target.value;
    
                if (e.target.checked) {
                    // Dodaj samochód do listy porównania
                    compareList.push(carId);
                } else {
                    // Usuń samochód z listy porównania
                    const index = compareList.indexOf(carId);
                    if (index > -1) {
                        compareList.splice(index, 1);
                    }
                }
    
                // Przekaż listę samochodów do porównania do URL
                const compareUrl = new URL(window.location.protocol + "//" + window.location.host + "/compare/");
                compareList.forEach(id => compareUrl.searchParams.append('compare', id));
    
                // Zaktualizuj przycisk porównania
                const compareButton = document.getElementById('compare-button');
                if (compareList.length >= 2) {
                    compareButton.disabled = false;
                    compareButton.href = compareUrl.href;
                } else {
                    compareButton.disabled = true;
                    compareButton.href = '#';
                }
            });
        });
    });
    </script>
    
    

{% endblock %}

home/templates/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

     <title>AutoDealerPro</title>

     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

     <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">
     <link rel="stylesheet" href="{% static 'home/css/owl.carousel.css' %}">
     <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
     <link rel="stylesheet" href="{% static 'home/css/style2.css' %}">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/css/bootstrap-select.min.css">

     <!-- MAIN CSS -->
     <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

     <!-- PRE LOADER -->
     <section class="preloader">
          <div class="spinner">
               <span class="spinner-rotate"></span>
          </div>
     </section>

     

     <!-- MENU -->
     <section class="navbar custom-navbar navbar-fixed-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="{% url 'home:home' %}" class="navbar-brand">Nazwa komisu</a>
               </div>

               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-nav-first">
                         <li><a href="{% url 'home:home' %}">Strona główna</a></li>
					<li><a href="{% url 'home:car-list' %}">Samochody</a></li>
                         <li><a href="{% url 'home:faq' %}">FAQ</a></li>
                         <li><a href="{% url 'home:partner-list' %}">Lista partnerów</a></li>
                         <!-- <li><a href="#">Kontakt</a></li> -->
                    </ul>
               </div>

          </div>
     </section>

     {% block content %}{% endblock %}

     <!-- FOOTER -->
     <footer id="footer">
          <div class="container">
               <div class="row">

                    <div class="col-md-4 col-sm-6">
                         <div class="footer-info">
                              <div class="section-title">
                                   <h2>Nazwa firmy</h2>
                              </div>
                              <address>
                                   <p>Przykładowy adres <br>00-000 Miasto</p>
                              </address>

                              <ul class="social-icon">
                                   <li><a href="#" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                                   <li><a href="#" class="fa fa-twitter"></a></li>
                                   <li><a href="#" class="fa fa-instagram"></a></li>
                              </ul>

                              <div class="copyright-text"> 
                                   <p>Copyright &copy; 2023 Auto Dealer Pro</p>
                              </div>
                         </div>
                    </div>

                    <div class="col-md-4 col-sm-6">
                         <div class="footer-info">
                              <div class="section-title">
                                   <h2>Kontakt</h2>
                              </div>
                              <address>
                                   <p>+48 333 404 556</p>
                                   <p><a href="mailto:contact@company.com">autodealerpro@company.com</a></p>
                              </address>

                              <div class="footer_menu">
                                   <h2>Szybkie linki</h2>
                                   <ul>
                                        <li><a href="{% url 'home:home' %}">Strona główna</a></li>
                                        <li><a href="{% url 'home:car-list' %}">Lista pojazdów</a></li>
                                        <li><a href="{% url 'home:financing' %}">Finansowanie</a></li>
                                        <li><a href="{% url 'home:add-opinion' %}">Dodaj opinie</a></li>
                                        <li><a href="{% url 'members:login-user' %}">Login</a></li>
                                   </ul>
                              </div>
                         </div>
                    </div>

                    <div class="col-md-4 col-sm-12">
                         <div class="footer-info newsletter-form">
                              <div class="section-title">
                                   <h2>Newsletter</h2>
                              </div>
                              <div>
                                   <div class="form-group">
                                        <form action="#" method="get">
                                             <input type="email" class="form-control" placeholder="Podaj swój mail" name="email" id="email" required>
                                             <input type="submit" class="form-control" name="submit" id="form-submit" value="Zapisz">
                                        </form>
                                        <span><sup>*</sup> Nasz newsletter to nie spam. Otrzymujesz tylko konkrety</span>
                                   </div>
                              </div>
                         </div>
                    </div>
                    
               </div>
          </div>
     </footer>


     <!-- SCRIPTS -->
     <script src="{% static 'home/js/jquery.js' %}"></script>
     <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'home/js/smoothscroll.js' %}"></script>
     <script src="{% static 'home/js/custom.js' %}"></script>
     <script src="https://kit.fontawesome.com/e1dad58639.js" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/bootstrap-select.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.18/js/i18n/defaults-pl_PL.min.js"></script>
     <script>
          $(document).ready(function() {
              $('.selectpicker').selectpicker({
                  language: 'pl_PL'
              });
          });
      </script>

</body>
</html>