admin_panel/urls.py
from django.urls import path
from admin_panel import views

app_name = 'admin_panel'

urlpatterns = [
    path('', views.home, name='home'),
    path('cars/', views.cars, name='cars'),
    path('cars/show-car/<int:car_id>/', views.show_car, name='show-car'),
    path('cars/add-car/', views.add_car, name='add-car'),
    path('cars/del-car/<int:car_id>/', views.del_car, name='del-car'),
    path('cars/edit-car/<car_id>', views.edit_car, name='edit-car'),
    path('cars/cars-on-sale/', views.car_on_sale, name='cars-on-sale'),
    path('cars/cars-on-sale/add-car-on-sale', views.add_car_on_sale, name='add-car-on-sale'),
    path('cars/cars-on-sale/del-car-on-sale/<int:car_id>/', views.del_car_on_sale, name='del-car-on-sale'),
    path('cars/car-reservations', views.car_reservations, name='car-reservations'),
    path('cars/car-reservations/add-car-reservation', views.add_car_reservation, name='add-car-reservation'),
    path('clients/', views.clients, name='clients'),
    path('clients/add-client/', views.add_client, name='add-client'),
    path('clients/show-client/<int:client_id>/', views.show_client, name='show-client'),
    path('clients/edit-client/<client_id>/', views.edit_client, name='edit-client'),
    path('clients/del-client/<int:client_id>/', views.del_client, name='del-client'),
    path('clients/opinions/', views.opinions, name='opinions'),
    path('clients/opinions/del-opinion/<int:opinion_id>/', views.del_opinion, name='del-opinion'),
    path('contact/', views.contact, name='contact'),
    path('transaction/', views.transaction, name='transaction'),
    path('transaction/show-transaction/<int:transaction_id>/', views.show_transaction, name='show-transaction'),
    path('transaction/add-transaction/', views.add_transaction, name='add-transaction'),
    path('transaction/edit-transaction/<int:transaction_id>/', views.edit_transaction, name='edit-transaction'),
    path('transaction/del-transaction/<int:transaction_id>/', views.del_transaction, name='del-transaction'),
    path('contract/<int:transaction_id>/', views.contract_view, name='contract'),
    path('report_view/', views.report_view, name='report_view'),
    path('sales_report/', views.sale_report_view, name='sales_report'),
    path('contact/mark_as_answered/<int:contact_id>/', views.mark_as_answered, name='mark_as_answered'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('dashboard/', include('admin_panel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('faq', views.FAQ, name='faq'),
    path('index', views.index, name='index'),
    path('car-list', views.car_list, name='car-list'),
    path('car_list/car_details/<int:car_id>', views.car_details, name='car_details'),
    path('partner-list', views.partner_list, name='partner-list'),
    path('add-opinion', views.add_opinion, name='add-opinion'),
    path('financing', views.financing, name='financing'),
    path('compare/', views.compare, name='compare'),
]

admin_panel/models.py
from django.db import models
from home.models import *

class DEALER(models.Model):
    name = models.CharField(max_length=250)
    nip = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=250)
    bank = models.CharField(max_length=250)
    bank_account = models.CharField(max_length=250)

    def __str__ (self):
        return self.name

class Transaction(models.Model):
    dealer = DEALER.objects.first()
    client = models.ForeignKey(Clients, on_delete=models.CASCADE, related_name='transactions', db_index=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='transactions', db_index=True)
    date = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_paid = models.BooleanField(default=False)

    def __str__ (self):
        return f"{self.client.name} | {self.car.make} {self.car.model}"
    
class CarReservation(models.Model):
    client = models.ForeignKey(Clients, on_delete=models.CASCADE, related_name='reservations', db_index=True)
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='reservations', db_index=True)
    date = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField()
    end_date = models.DateField()
    is_paid = models.BooleanField(default=False)

    def __str__ (self):
        return f"{self.client.name} | {self.car.make} {self.car.model}"

home/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save

class CarFuelType(models.Model):
    fuel_type = models.CharField('Rodzaj paliwa', max_length=50)

    def __str__(self):
        return self.fuel_type
    
class CarGear(models.Model):
    gear = models.CharField('Skrzynia biegów', max_length=50)

    def __str__(self):
        return self.gear
    
class vehicle_make(models.Model):
    make = models.CharField('Marka', max_length=50)

    def __str__(self):
        return self.make\
        
class yes_no(models.Model):
    yes_no = models.CharField('Wartość', max_length=3)

    def __str__(self):
        return self.yes_no



class Car(models.Model):
    car_make = [
        ('Audi', 'Audi'),
        ('BMW', 'BMW'),
        ('Ford', 'Ford'),
        ('Honda', 'Honda'),
        ('Hyundai', 'Hyundai'),
        ('Kia', 'Kia'),
        ('Mazda', 'Mazda'),
        ('Mercedes-Benz', 'Mercedes-Benz'),
        ('Nissan', 'Nissan'),
        ('Opel', 'Opel'),
        ('Renault', 'Renault'),
        ('Skoda', 'Skoda'),
        ('Toyota', 'Toyota'),
        ('Tesla', 'Tesla'),
        ('Volkswagen', 'Volkswagen'),
    ]

    fuel_type = [
        ('benzyna', 'Benzyna'),
        ('diesel', 'Diesel'),
        ('hybryda', 'Hybryda'),
        ('elektryczny', 'Elektryczny'),
        ('lpg', 'LPG'),
    ]

    gear_type = [
        ('Manualna', 'Manualna'),
        ('Automatyczna', 'Automatyczna'),
    ]

    type = [
        ('Używane', 'Używane'),
        ('Nowe', 'Nowe'),
    ]

    color = [
        ('Biały', 'Biały'),
        ('Szary', 'Szary'),
        ('Czarny', 'Czarny'),
        ('Srebrny', 'Srebrny'),
        ('Niebieski', 'Niebieski'),
        ('Czerwony', 'Czerwony'),
        ('Zielony', 'Zielony'),
        ('Żółty', 'Żółty'),
        ('Brązowy', 'Brązowy'),
        ('Inny', 'Inny')
    ]

    seats = [
        ('2', '2'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7 lub wiecej', '7 lub wiecej'),
    ]

    doors = [
        ('2/3', '2/3'),
        ('4/5', '4/5'),
    ]

    make = models.CharField('Marka', max_length=50, choices=car_make)
    model = models.CharField('Model', max_length=50)
    vin = models.CharField('VIN', max_length=17)
    year = models.IntegerField('Rok produkcji')
    price = models.IntegerField('Cena (PLN)')
    mileage = models.IntegerField('Przebieg (km)')
    description = models.TextField('Opis')
    engine_capacity = models.IntegerField('Pojemność silnika (cm3)')
    engine_power = models.IntegerField('Moc silnika (KM)')
    fuel_type = models.CharField('Rodzaj paliwa', max_length=50, choices=fuel_type)
    gear = models.CharField('Skrzynia biegów', max_length=50, choices=gear_type)
    type = models.CharField('Typ', max_length=50, choices=type)
    color = models.CharField('Kolor', max_length=50, choices=color)
    seats = models.CharField('Liczba miejsc', max_length=50, choices=seats)
    doors = models.CharField('Liczba drzwi', max_length=50, choices=doors)
    availability = models.BooleanField('Dostępność', default=False)
    image = models.ImageField('Zdjęcia', upload_to='images/',blank=True, null=True)

    def __str__(self):
        return str(self.make) + ' ' + self.model
    

class CarOnSale(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    special_offer = models.BooleanField('Promocja', default=False)
    new_price = models.IntegerField('Nowa cena (PLN)', blank=True, null=True)
    start_date = models.DateField('Data rozpoczęcia', blank=True, null=True)
    end_date = models.DateField('Data zakończenia', blank=True, null=True)
    
    def __str__(self):
        return str(self.car)
    
class Clients(models.Model):
    name = models.CharField('Imię i nazwisko / Nazwa firmy', max_length=50)
    pesel = models.IntegerField('PESEL', blank=True, null=True)
    nip = models.IntegerField('NIP', blank=True, null=True)
    adress = models.CharField('Adres', max_length=100)
    city = models.CharField('Miasto', max_length=50)
    zip = models.IntegerField('Kod pocztowy')
    phone = models.IntegerField('Telefon')
    email = models.EmailField('Email')
    

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    name = models.CharField('Imię i nazwisko', max_length=50)
    adress = models.CharField('Adres', max_length=100)
    city = models.CharField('Miasto', max_length=50)
    zip = models.IntegerField('Kod pocztowy')
    phone = models.IntegerField('Telefon')
    email = models.EmailField('Email')
    position = models.CharField('Stanowisko', max_length=50)
    hire_date = models.DateField('Data zatrudnienia')
    fire_date = models.DateField('Data zwolnienia', blank=True, null=True)
    
    def __str__(self):
        return self.name
    
class Order_status(models.Model):
    status = models.CharField('Status', max_length=50)
    
    def __str__(self):
        return self.status

class Orders(models.Model):
    order_number = models.BigAutoField(primary_key=True)
    client = models.ForeignKey(Clients, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    order_date = models.DateField('Data transakcji')
    order_price = models.IntegerField('Kwota transakcji')
    order_status = models.ForeignKey(Order_status, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.client.name + ' | ' + self.car.make + ' ' + self.car.model
 
class Contact(models.Model):
    name = models.CharField('Imię i nazwisko', max_length=50)
    email = models.EmailField('Email')
    message = models.TextField('Wiadomość')
    answer = models.ForeignKey(yes_no, on_delete=models.CASCADE, default=1)
    
    def __str__(self):
        return self.name

class client_opinion(models.Model):
    SCORE_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]

    client_name = models.CharField(max_length=100)
    client_mail = models.EmailField(max_length=100)
    client_score = models.CharField(choices=SCORE_CHOICES, max_length=1)
    client_opinion = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    rodo = models.BooleanField()
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.client_name

home/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from .filters import CarFilter
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages


def home(request):
    submitted = False
    opinion = client_opinion.objects.all()
    caronsale = CarOnSale.objects.all()
    car = Car.objects.all()
    today = timezone.now().date()

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return HttpResponseRedirect('/index?submitted=True')
    else:
        contact_form = ContactForm
        if "submitted" in request.GET:
            submitted = True

    return render(request, 'index.html',
                  {'contact_form': contact_form, 'submitted': submitted, 'opinion': opinion, 'caronsale': caronsale, 'car': car, 'today': today})



def FAQ(request):
    return render(request, 'FAQ.html', {})

def index(request):
    submitted = False
    opinion = client_opinion.objects.all()
    caronsale = CarOnSale.objects.all()
    car = Car.objects.all()
    today = timezone.now().date()

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            return HttpResponseRedirect('/index?submitted=True')
    else:
        contact_form = ContactForm
        if "submitted" in request.GET:
            submitted = True

    return render(request, 'index.html',
                  {'contact_form': contact_form, 'submitted': submitted, 'opinion': opinion, 'caronsale': caronsale, 'car': car, 'today': today})

def car_list(request):
    car_list = Car.objects.all()

    # Filtering
    car_filter = CarFilter(request.GET, queryset=car_list)
    car_list = car_filter.qs

    # Sorting
    sort_by = request.GET.get('sort_by')

    if sort_by in ['make', 'model', 'price', 'year']:
        car_list = car_list.order_by(sort_by)
    
    return render(request, 'Car_List.html', 
                  {'car_list': car_list, 'filter': car_filter})



def car_details(request, car_id):
    car = Car.objects.get(pk=car_id)
    return render(request, 'Car_Details.html', 
                  {'car': car})

def partner_list(request):
    return render(request, 'partner_list.html', {})

def add_opinion(request):
    submitted = False
    
    if request.method == 'POST':
        form = ClientOpinionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Pojawiła się nowa opinia')
            return HttpResponseRedirect(reverse('home:home') + '?submitted=True')
    else:
        form = ClientOpinionForm
        if "submitted" in request.GET:
            submitted = True

    return render(request, 'add_opinion.html',
                  {'form': form, 'submitted': submitted})

def financing(request):
    return render(request, 'financing.html', {})

def compare(request):
    compare_list = request.GET.getlist('compare')
    car_list = Car.objects.filter(id__in=compare_list)
    return render(request, 'compare.html', {'car_list': car_list})

admin_panel/templates/cars.html
{% extends 'base.html' %}

{% block title %} Lista samochodów {% endblock %}

{% block content %}
    
{% if messages %}
    {% for message in messages %}
        {% if 'success' in message.tags %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </div>
        {% elif 'error' in message.tags %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Lista samochodów
                <a href="{% url 'admin_panel:add-car' %}" class="btn btn-primary btn-icon-split btn-sm float-right">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Dodaj samochód</span>
                </a>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Marka</th>
                            <th>Model</th>
                            <th>Rok produkcji</th>
                            <th>Przebieg</th>
                            <th>Paliwo</th>
                            <th>Moc</th>
                            <th>Cena</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for car in car_list %}
                            <tr>
                                <td>
                                    {% if car.availability %}
                                        <i class="fas fa-check-circle text-success"></i>
                                    {% else %}
                                        <i class="fas fa-times-circle text-danger"></i>
                                    {% endif %}
                                    {% if car.reserved %}
                                        <i class="text-danger">REZERWACJA</i>
                                    {% endif %}
                                </td>
                                <td>{{ car.make }}</td>
                                <td>{{ car.model}}</td>
                                <td>{{ car.year}}</td>
                                <td>{{ car.mileage}} km</td>
                                <td>{{ car.fuel_type}}</td>
                                <td>{{ car.engine_power}} KM</td>
                                <td>{{ car.price }} PLN</td>
                                <td>
                                    <a href="{% url 'admin_panel:show-car' car.id %}" class="btn btn-primary btn-icon-split btn-sm">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-eye"></i>
                                        </span>
                                    </a>
                                    <a href="{% url 'admin_panel:edit-car' car.id %}" class="btn btn-primary btn-icon-split btn-sm">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                    </a>
                                    <a href="#" class="btn btn-danger btn-squere btn-sm" data-toggle="modal" data-target="#deleteModal{{ car.id }}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>

                            <!-- Modal -->
                            <div class="modal fade" id="deleteModal{{ car.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ car.id }}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel{{ car.id }}">Potwierdzenie usunięcia samochodu</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Czy na pewno chcesz {{car.make}} {{car.model}}?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                                            <a href="{% url 'admin_panel:del-car' car.id %}" class="btn btn-danger">Usuń</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock %}

admin_panel/templates/clients.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Lista samochodów {% endblock %}

{% block content %}
    
{% if messages %}
    {% for message in messages %}
        {% if 'success' in message.tags %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </div>
        {% elif 'error' in message.tags %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">

            <h6 class="m-0 font-weight-bold text-primary">
                Lista klientów
                <a href="{% url 'admin_panel:add-client' %}" class="btn btn-primary btn-icon-split btn-sm float-right">
                    <span class="icon text-white-50">
                        <i class="fas fa-plus"></i>
                    </span>
                    <span class="text">Dodaj klienta</span>
                </a>
                <button id="filter-toggle" class="btn btn-primary btn-icon-split btn-sm float-right mr-2">
                    <span class="text">FILTRY</span>
                </button>
                
            </h6>
            <div id="filter-form" style="display: none;">
                <form method="GET">
                    <input type="text" name="name" placeholder="Imię i nazwisko / Nazwa firmy" value="{{ request.GET.name }}">
                    <input type="text" name="pesel" placeholder="PESEL" value="{{ request.GET.pesel }}">
                    <input type="text" name="nip" placeholder="NIP" value="{{ request.GET.nip }}">
                    <input type="text" name="adress" placeholder="Adres" value="{{ request.GET.adress }}">
                    <input type="text" name="city" placeholder="Miasto" value="{{ request.GET.city }}">
                    <input type="text" name="zip" placeholder="Kod pocztowy" value="{{ request.GET.zip }}">
                    <input type="text" name="phone" placeholder="Telefon" value="{{ request.GET.phone }}">
                    <input type="text" name="email" placeholder="E-mail" value="{{ request.GET.email }}">
                    <button type="submit" class="btn btn-primary">Filtruj</button>
                </form>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th><a href="?order_by=name{% if order_by == 'name' %}&desc=True{% endif %}">Imię i nazwisko<br>/ Nazwa firmy</a></th>
                            <th><a href="?order_by=pesel{% if order_by == 'pesel' %}&desc=True{% endif %}">PESEL</a></th>
                            <th><a href="?order_by=nip{% if order_by == 'nip' %}&desc=True{% endif %}">NIP</a></th>
                            <th><a href="?order_by=adress{% if order_by == 'adress' %}&desc=True{% endif %}">Adres</a></th>
                            <th><a href="?order_by=city{% if order_by == 'city' %}&desc=True{% endif %}">Miasto</a></th>
                            <th><a href="?order_by=zip{% if order_by == 'zip' %}&desc=True{% endif %}">Kod pocztowy</a></th>
                            <th><a href="?order_by=phone{% if order_by == 'phone' %}&desc=True{% endif %}">Telefon</a></th>
                            <th><a href="?order_by=email{% if order_by == 'email' %}&desc=True{% endif %}">E-mail</a></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Imię i nazwisko<br>/ Nazwa firmy</th>
                            <th>PESEL</th>
                            <th>NIP</th>
                            <th>Adres</th>
                            <th>Miasto</th>
                            <th>Kod pocztowy</th>
                            <th>Telefon</th>
                            <th>E-mail</th>
                            <th></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for clients in clients %}
                            <tr>       
                                <td>{{clients.name}}</td>
                                {% if clients.pesel == None %}
                                    <td>-</td>
                                {% else %}
                                    <td>{{clients.pesel}}</td>
                                {% endif %}
                                {% if clients.nip == None %}
                                    <td>-</td>
                                {% else %}
                                    <td>{{clients.nip}}</td>
                                {% endif %}
                                <td>{{clients.adress}}</td>
                                <td>{{clients.city}}</td>
                                <td>{{clients.zip}}</td>
                                <td>{{clients.phone}}</td>
                                <td>{{clients.email}}</td>
                                <td>
                                    <a href="{% url 'admin_panel:show-client' clients.id %}" class="btn btn-primary btn-icon-split btn-sm">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-eye"></i>
                                        </span>
                                    </a>
                                    <a href="{% url 'admin_panel:edit-client' clients.id %}" class="btn btn-primary btn-icon-split btn-sm">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-edit"></i>
                                        </span>
                                    </a>
                                    <a href="#" class="btn btn-danger btn-squere btn-sm" data-toggle="modal" data-target="#deleteModal{{ clients.id }}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                            </tr>

                            <!-- Modal -->
                            <div class="modal fade" id="deleteModal{{ clients.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ clients.id }}" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel{{ clients.id }}">Potwierdzenie usunięcia klienta</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            Czy na pewno chcesz usunąć dane: {{ clients.name }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Anuluj</button>
                                            <a href="{% url 'admin_panel:del-client' clients.id %}" class="btn btn-danger">Usuń</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <script>
        document.getElementById('filter-toggle').addEventListener('click', function() {
            var form = document.getElementById('filter-form');
            if(form.style.display === 'none') {
                form.style.display = 'block';
            } else {
                form.style.display = 'none';
            }
        });
    </script>

{% endblock %}

admin_panel/templates/edit_client.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block title_v2 %}{% endblock %}

{% block content %}
    
<div class='container'>

    <h1>Edytuj dane klienta:</h1>
        <form action="" method=POST>
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Akceptuj" class="btn btn-secondary">
        </form> 
        <br>
</div>    
    
{% endblock %}

admin_panel/templates/report.html
{% extends 'base.html' %}

{% block title %} Dashboard {% endblock %}

{% block title_v2 %} Raport sprzedaży {% endblock %}

{% block content %}

<div class="container py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form method="POST" class="mb-4">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_month">Miesiąc</label>
                        {{ form.month }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_year">Rok</label>
                        {{ form.year }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Generuj Raport</button>
            </form>
            {% if no_sales %}
                <div class="alert alert-warning" role="alert">
                    Nie ma żadnych transakcji za wybrany miesiąc.
                </div>
            {% elif transactions %}
                <h2>Raport za {{ form.month.value }}/{{ form.year.value }}</h2>
                <h3>Ilość sprzedanych samochodów: {{ total_sales }}</h3>
                <ul class="list-group">
                    {% for transaction in transactions %}
                        <li class="list-group-item">{{ transaction }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}